[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200